class Config:

    URL = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'
    USERNAME = 'Admin'
    PASSWORD = 'admin123'
    DRIVER_PATH = '.\\drivers\\chrome\\chromedriver.exe'
    INVALID_PASSWORD = 'admin123xyz'
    ERROR_TEXT = 'Invalid credentials'
    LOGIN_LABEL_TEXT = 'Login'
    USERNAME_LABEL_TEXT = 'Username'
    PASSWORD_LABEL_TEXT = 'Password'
    FORGET_PASSWORD_LABEL = 'Forgot your password?'
    FOOTER_TEXT1_LABEL = 'OrangeHRM OS 5.2'
    FOOTER_TEXT2_LABEL = '© 2005 - 2022 OrangeHRM, Inc. All rights reserved.'
    ATTRIBUTE_NAME = 'src'
    ORANGE_HRM_LOGO = 'ohrm_branding.png'
    USER_ATTRIBUTE_NAME = 'placeholder'
    PASS_ATTRIBUTE_NAME = 'placeholder'
    USER_ATTRIBUTE_VALUE = 'Username'
    PASS_ATTRIBUTE_VALUE = 'Password'
    REQUIRED_TEXT = 'Required'
    HR_FOR_ALL = 'ohrm_logo.png'